---
title: "Bivariate Plot"
author: "Chuhan Liu"
date: "2/6/2022"
output: html_document
---

Categorical-Categorical PLOT
```{r}
library(rio)

# collecting the data
location='https://github.com/chuhanl/Visual-Analytics/raw/main/'
file='ACS%202019%20weighted%20subsample.dta'
link=paste0(location,file)
mydata=import(link)
```

```{r}
#sex table of marital status counts
(SexMarst=table(mydata$marst,mydata$sex))

#reorganize data
SexMarst[1,1]=SexMarst[1,1]+SexMarst[2,1]
SexMarst[1,2]=SexMarst[1,2]+SexMarst[2,2]
SexMarst[3,1]=SexMarst[3,1]+SexMarst[4,1]
SexMarst[3,2]=SexMarst[3,2]+SexMarst[4,2]

SexMarst=SexMarst[-2,]
SexMarst=SexMarst[-3,]

#rename rows and columns
newRowNames=c('Married','Separated/divorced','Widowed','Never married/single')
newColNames=c('Male','Female')
rownames(SexMarst) <- newRowNames
colnames(SexMarst) <- newColNames
```

```{r}
# computing marginal percent (per column)
library(magrittr)
(SexMarst_mgCol=prop.table(SexMarst,
                            margin = 2)%>%round(.,3))
```

```{r}
#making a data frame
SexMarstDF=as.data.frame(SexMarst)
names(SexMarstDF)=c("MaritalStatus","Sex","Counts")

#adding marginal percents:
SexMarstDF$Percent=as.data.frame(SexMarst_mgCol)[,3]

SexMarstDF
```

```{r}
# reorder levels
SexMarstDF$MaritalStatus=factor(SexMarstDF$MaritalStatus,
                           levels=c('Widowed','Separated/divorced','Married','Never married/single'))

library(ggplot2)
base1=ggplot(data=SexMarstDF, 
             aes(x=Sex, y=Percent,
                 fill=MaritalStatus))
```

Stack:
```{r}
barStacked = base1 + geom_bar(stat = "identity",
                              position = 'stack')
barStacked
```

```{r}
library(scales)
barStacked= barStacked + geom_text(size = 4,
                             position = position_stack(vjust = 0.5),
                             aes(label=percent(Percent,accuracy = 0.1)))

barStacked = barStacked + scale_y_continuous(labels = scales::percent)

barStacked +labs(title="Gender Gap in Marital Status",fill="Marital Status")
```
